### PR TITLE
Add argument masking

### PR DESCRIPTION
**Pull request by bilby91**

### CODE REVIEW

**Comment by bilby91** [comment]
Hello @exAspArk 👋

Let me know what you think about the change and if there is anything I'm missing. We are looking forward in taking advantage of this feature on our project!

Thanks!

**Comment by bilby91** [comment]
Ping @exAspArk

**Comment by exAspArk** [comment]
Hey @bilby91! Sorry for the delayed response.

Thanks for opening the PR. I'll take a look this week.

**Comment by bilby91** [comment]
@exAspArk Any chance you could review it ?

**Comment by bilby91** [comment]
Ping @exAspArk

**Comment by ghost** [comment]
This PR has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

**Comment by bilby91** [comment]
@exAspArk Any chance you could review this ?

**Comment by asgeo1** [comment]
@exAspArk, can we please reopen and merge this PR?  Seems to add very useful functionality. I'm using it myself now.

**Pull request closed without merging**
